# workflow的名字
name: Pack as mcaddon file
# 作者
author: RawDiamondMC
# 描述
description: 打包成mcaddon文件
# push的时候build
on: push

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: pack as zip file
      run: zip -r ExtraRecipeBedrock.zip ER-bp ER-rp