# workflow的名字
name: Pack as mcaddon file
# push的时候build
on: push

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: pack as zip file
        run: zip -r ExtraRecipeBedrock.zip ER-bp ER-rp