# workflow的名字
name: Pack as mcaddon file
# push的时候build
on: push

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Pack
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
